services:
  backend:
    build: backend
    ports:
      - 8081:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=test
      - PGUSER=test
      - POSTGRES_USER=test
    expose:
      - 5432
  frontend:
    build: frontend
    depends_on:
      - backend
    networks:
      - spring-postgres
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
volumes:
  db-data:
networks:
  spring-postgres:
