services:
  backend:
    build: 
      context: backend
      target: dev-envs
    ports:
      - 8081:8080
    environment:
      - POSTGRES_DB=ems
    networks:
      - spring-postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=ems
      - POSTGRES_PASSWORD=root
      - PGUSER=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  frontend:
    build: frontend
    depends_on:
      - backend
    networks:
      - spring-postgres
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

volumes:
  db-data:
networks:
  spring-postgres:
